Fix admin languages
vtex-apps/paginated-table pull request #48
Opened 2021-08-17 16:31 UTC by daniserejo

#### What is the purpose of this pull request?

Fix admin languages 

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2021-08-17 18:13 UTC, camilavcoutinho requested changes
@daniserejo, japanese and korean files are wrong. There is no ja-JA.json and ko-KO.json. You deleted the right ones ja-JP.json and ko-KR.json.

2021-09-20 16:06 UTC, camilavcoutinho approved these changes

2021-09-21 18:39 UTC, gabibguti commented on messages/bg.json
> +}
Do we need this file `bg.json`?

2021-09-21 18:51 UTC, gabibguti commented on CHANGELOG.md
> +
I think this CHANGELOG does not express clearly the changes we have done in this PR.
Correct me if I am wrong, but I would put it this way:

```
### Added

- I18n Bg.

### Changed

- I18n fr-FR.

### Fixed

- Indentation in I18n files (it-IT, ja-JP, ko-KR, nl-NL, ro-RO).

### Removed

- Unused I18n files (ar, bs, es-ar, es-es, fr, it, ja, ko, nl, rm, ro).
```

2021-09-22 17:03 UTC, gabibguti approved these changes

2021-09-23 14:21 UTC, merged